import type { Config } from './types';

export const CONFIG_DIR_NAME = 'paw';
export const CONFIG_FILE_NAME = 'config.json';

export const IPC_CHANNELS = {
  CONFIG_GET: 'config:get',
  CONFIG_SET: 'config:set',
  CONFIG_CHANGED: 'config:changed',
  SHELL_SPAWN: 'shell:spawn',
  SHELL_DATA: 'shell:data',
  SHELL_RESIZE: 'shell:resize',
  SHELL_INPUT: 'shell:input',
  SHELL_KILL: 'shell:kill',
  SHELL_CWD: 'shell:cwd',
  CLIPBOARD_WRITE: 'clipboard:write',
  THEME_GET_SYSTEM: 'theme:getSystem',
  THEME_SYSTEM_CHANGED: 'theme:systemChanged',
  WINDOW_STATE: 'window:state',
  WINDOW_TOGGLE_MAXIMIZE: 'window:toggleMaximize',
} as const;

export const DEFAULT_CONFIG: Config = {
  theme: 'auto',
  autoAppearance: true,
  scrollback: 10000,
  font: {
    family: 'Menlo, Monaco, "Courier New", monospace',
    size: 14,
    lineHeight: 1.2,
  },
  opacity: 1.0,
  cursorStyle: 'block',
  cursorBlink: true,
  copyMode: {
    enterKey: 'c',
    enterModifiers: ['ctrl', 'shift'],
    macModifiers: ['meta', 'shift'],
    winModifiers: ['ctrl', 'shift'],
  },
  window: {
    width: 900,
    height: 600,
  },
  shellArgs: [],
  customThemes: [],
};

export const BUILTIN_THEMES = [
  {
    id: 'dracula',
    name: 'Dracula',
    type: 'dark',
    colors: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      cursorAccent: '#282a36',
      selectionBackground: '#44475a',
      selectionForeground: '#f8f8f2',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    type: 'dark',
    colors: {
      background: '#282c34',
      foreground: '#abb2bf',
      cursor: '#528bff',
      cursorAccent: '#282c34',
      selectionBackground: '#3e4451',
      selectionForeground: '#abb2bf',
      black: '#282c34',
      red: '#e06c75',
      green: '#98c379',
      yellow: '#e5c07b',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
      white: '#abb2bf',
      brightBlack: '#545862',
      brightRed: '#e06c75',
      brightGreen: '#98c379',
      brightYellow: '#e5c07b',
      brightBlue: '#61afef',
      brightMagenta: '#c678dd',
      brightCyan: '#56b6c2',
      brightWhite: '#c8ccd4',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    type: 'dark',
    colors: {
      background: '#002b36',
      foreground: '#839496',
      cursor: '#93a1a1',
      cursorAccent: '#002b36',
      selectionBackground: '#073642',
      selectionForeground: '#93a1a1',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    type: 'light',
    colors: {
      background: '#fdf6e3',
      foreground: '#657b83',
      cursor: '#586e75',
      cursorAccent: '#fdf6e3',
      selectionBackground: '#eee8d5',
      selectionForeground: '#586e75',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    type: 'dark',
    colors: {
      background: '#282828',
      foreground: '#ebdbb2',
      cursor: '#ebdbb2',
      cursorAccent: '#282828',
      selectionBackground: '#3c3836',
      selectionForeground: '#ebdbb2',
      black: '#282828',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#a89984',
      brightBlack: '#928374',
      brightRed: '#fb4934',
      brightGreen: '#b8bb26',
      brightYellow: '#fabd2f',
      brightBlue: '#83a598',
      brightMagenta: '#d3869b',
      brightCyan: '#8ec07c',
      brightWhite: '#ebdbb2',
    },
  },
];

export const COPY_MODE_COMMANDS = [
  'moveLeft', 'moveRight', 'moveDown', 'moveUp',
  'moveWordForward', 'moveWordBackward',
  'moveWordForwardBig', 'moveWordBackwardBig',
  'moveLineStart', 'moveLineStartNonBlank', 'moveLineEnd',
  'moveFirstLine', 'moveLastLine', 'moveScreenTop', 'moveScreenMiddle', 'moveScreenBottom',
  'scrollHalfPageDown', 'scrollHalfPageUp', 'scrollPageDown', 'scrollPageUp',
  'enterVisual', 'enterVisualLine', 'yank', 'searchForward', 'searchBackward',
  'nextSearch', 'prevSearch', 'exit', 'noop',
] as const;

export type CopyModeCommand = typeof COPY_MODE_COMMANDS[number];
